### ISSUE TITLE
Fix year filter

### ISSUE THREAD

**Issue by lmcjt37** [lmcjt37/curated-tv-and-film#104]
When you remove tv shows in the filters, a year input is revealed.

This doesn't work.

**Comment by davidlamt** [comment]
Hi, I am interested in working on this. I am thinking about implementing a "progressive" year search and wanted your thoughts on that.

For instance, a "201" search will result in movies created in the 2010s (2010, 2011, etc.). A full year search ("2014") should work normally.

**Comment by lmcjt37** [comment]
@davidlamt that sounds like a decent approach. The current main search works the same way. You have the logic there too.

**Comment by yamitrvg12** [comment]
I made a PR resolving this issue and I did some improvements, more friendly to use.
