### ISSUE TITLE
Scroll animation

### ISSUE THREAD

**Issue by lmcjt37** [lmcjt37/curated-tv-and-film#105]
When you click on the header title, the scroll to top just jumps there which is clunky.

An easing should be applied to smooth this out.

**Comment by pranay414** [comment]
@lmcjt37 I would like to work on this.

**Comment by lmcjt37** [comment]
@pranay414 go for it, marking as claimed.

**Comment by pranay414** [comment]
@lmcjt37 Please have a look at my PR.
