### ISSUE TITLE
Improve UI/UX

### ISSUE THREAD

**Issue by lmcjt37** [lmcjt37/curated-tv-and-film#16]
The web app is currently very simple and could do with a facelift to make it more friendly.

Some suggestive tasks:
- [ ] Add improved styling to the page
- [x] Better Font
- [ ] Filter list (years, tv/film, animated, etc)

**Comment by Captain-DarkO** [comment]
I can do some styling here.

**Comment by Amit3200** [comment]
i can design ui but would need to develop
have a look at my work at https://amit3200.github.io/amit3200.io/

**Comment by lmcjt37** [comment]
@Amit3200 This has already been claimed - but you're welcome to have a go anyway, or make suggestions for others to use

**Comment by lmcjt37** [comment]
Going to close this ticket and re-open separate issues on remaining tasks.
