### ISSUE TITLE
Improve information displayed for TV/Film

### ISSUE THREAD

**Issue by lmcjt37** [lmcjt37/curated-tv-and-film#17]
There appears to be a lot of white space around the TV and Film sections.

Could do with either changing the placement of how information is shown or adding more information.

**Comment by Jeff-Duke** [comment]
I can add these changes if this is still up for grabs

**Comment by lmcjt37** [comment]
@Jeff-Duke feel free to have a stab - first come first serve IMO 😄

**Comment by Jeff-Duke** [comment]
PR open: https://github.com/lmcjt37/curated-tv-and-film/pull/40
