### ISSUE TITLE
QA | Improve tests

### ISSUE THREAD

**Issue by lmcjt37** [lmcjt37/curated-tv-and-film#20]
The tests use Jest.

Currently only the simplest `App.js` test exists from boilerplate CRA.

Would be good to improve tests throughout.

**Comment by jnelson180** [comment]
I'll make a PR with some Jest tests.

**Comment by lmcjt37** [comment]
I have added the basic snapshot tests for the components I have separated out.

Further tests required for methods.

**Comment by CometS1** [comment]
I would like to make some tests for the methods. Do you know how to test to see how the state has changed?

**Comment by lmcjt37** [comment]
You should be able to do a `shallow` render of the component. Then `expect` the state to change after a method call, checking this before and after.

eg. You have a state of disabled for `<Component/>`
it(‘should change state’, () => {
  const wrapper = shallow(<Component />);
  
  expect(wrapper.state().disabled).toEqual(true);
  
  wrapper.instance().method(); (I believe, you may need to spy on the method)

  expect(wrapper.state().disabled).toEqual(false);
});

**Comment by CometS1** [comment]
I was making a test for the showFilters state to see whether the toggle would change its state, and managed to get it working on a previous version, but when I updated to the current version of the repository, it now says that it no longer can read the state. Here is my current code:

`it('testing for changed toggle state', () => {
  const wrapper = shallow(<App />);
  
  expect(wrapper.state().showFilters).toEqual(false);
  
  wrapper.instance().toggleFilter();

  expect(wrapper.state().showFilters).toEqual(true);
}); `

And I get the error "Cannot read property 'showFilters' of null". Do you know if any recent changes would have caused it?

**Comment by lmcjt37** [comment]
Closing as most cases are covered.
