### ISSUE TITLE
UI | New favicon

### ISSUE THREAD

**Issue by lmcjt37** [lmcjt37/curated-tv-and-film#243]
Add/create a new favicon to represent the sites purpose.

The purpose of the site is to highlight top picks from films and tv shows and more specifically scenes from those chosen.

**Comment by lmcjt37** [comment]
@pavankalyan-codes assigned 👍🏻

**Comment by sowmiya-venkatesan** [comment]
May i work on this?

**Comment by sowmiya-venkatesan** [comment]
> @sowmiya-venkatesan Sure, @pavankalyan-codes unassigned himself so it's free.

Please do check this @lmcjt37 

> Figma link - https://www.figma.com/file/1rTKRgkdwGuHr8FbJ8caJL/Curated-logo?node-id=0%3A1

**Comment by lmcjt37** [comment]
@sowmiya-venkatesan The 5th icon looks good 👍🏻 like the placement of the play icon.
