### ISSUE TITLE
Tech | Refactor components

### ISSUE THREAD

**Issue by lmcjt37** [lmcjt37/curated-tv-and-film#244]
Refactor components to follow more modern coding patterns and practices such as arrow functions, hooks, etc.

**Comment by jason1985** [comment]
Hi I'd like to give this a try if possible.

Thanks.

**Comment by lmcjt37** [comment]
@jason1985 assigned. Good luck!

You don't have to do every single component, just as many as you feel comfortable with. I will raise another ticket to complete the remaining in that case.

**Comment by lmcjt37** [comment]
Of course. That makes complete sense.

I'm sure whatever you do will be an improvement on this repo 😅
