### ISSUE TITLE
UI | Only show delete when text in searchbar

### ISSUE THREAD

**Issue by lmcjt37** [lmcjt37/curated-tv-and-film#261]
If there is no text in the search bar then the 'close' icon should be hidden.

When something is typed into the searchbar then we should show the 'close' icon.

**Comment by pratik9333** [comment]
Hey, I have solved the issue and creating pull req :)

**Comment by pratik9333** [comment]
Thanks for assigning, loved to worked on it and one tip you can use Context API for state management rather than prop drilling. NVM thanks @lmcjt37

**Comment by lmcjt37** [comment]
@pratik9333 closing now issue is fixed. Thanks for all your work and working through the reviews for me.

> Thanks for assigning, loved to worked on it and one tip you can use Context API for state management rather than prop drilling.

When the repo was started the context API didn't exist. I will raise a ticket for someone to pick this up though.
