### ISSUE TITLE
Design | Better styling

### ISSUE THREAD

**Issue by lmcjt37** [lmcjt37/curated-tv-and-film#57]
Improve the look of the page with some sort of theming?

**Comment by lmcjt37** [comment]
@nSedrickm Go for it, I will mark as claimed.

**Comment by randylam87** [comment]
I could implement Material UI if you're looking for some sort of React frontend library.

**Comment by nSedrickm** [comment]
Good evening .I ran into this earlier while setting up the dev-server .checked the css code can't see a bug on that line.
Please what can I do to fix this .
![screenshot from 2018-10-29 21-41-19](https://user-images.githubusercontent.com/15856785/47680030-09400c00-dbc6-11e8-9422-f88d00182996.png)

**Comment by randylam87** [comment]
@nSedrickm It's likely due to the invalid css on line 172 of index.css

**Comment by nSedrickm** [comment]
Good morning .I corrected line 172 but still nothing.i get errors with npm install .I installed a few dependencies manually but one still remains .It says my version of linux isn't supported .
![screenshot from 2018-10-30 07-49-28](https://user-images.githubusercontent.com/15856785/47701094-04f10e80-dc19-11e8-90d5-dc1eb279974b.png)
![screenshot from 2018-10-30 07-50-29](https://user-images.githubusercontent.com/15856785/47701095-04f10e80-dc19-11e8-9293-564269f7d22f.png)

**Comment by lmcjt37** [comment]
@nSedrickm you could try removing the `node_modules` folder and re-installing again with `npm install --no-optional`, this might help run the project on your system. However it could have side effects if not all dependencies are installed.

**Comment by lmcjt37** [comment]
@CometS1 This is still an open issue yes.

The idea for this issue is to improve the page styling with some sort of theming.

You are welcome to commit any improvements you wish though :)

**Comment by CometS1** [comment]
Just a question, is `"REACT_APP_BUILD=debug react-scripts start"` suppose to be in the package.json file? Cause I have to remove it for the app to work

**Comment by CometS1** [comment]
For now, I modified it so that it is alphabetically organized and made pull request #168

**Comment by lmcjt37** [comment]
@CometS1 that's just one way of exposing environment variables to the build. It's not needed during development really and a simple check around it's use could produce the same result.

As a side note, it works on my machine 😉

**Comment by CometS1** [comment]
Alright, would it be ok to try to include a button that organizes it alphabetically?

**Comment by lmcjt37** [comment]
@CometS1 There is a filterBar which you could add something on there? Like a combo box to sort a-z and vice versa
