### ISSUE TITLE
Update all image URLs

### ISSUE THREAD

**Issue by lmcjt37** [lmcjt37/curated-tv-and-film#69]
Change all image URLs to static assets so that we gain uniformity. 

This will enable us to have more recognisable images from each of the entries to make it easier to find what you want.

**Comment by ManiacalBilby** [comment]
I'll work on this one.

**Comment by lmcjt37** [comment]
@ManiacalBilby You should raise another PR to add yourself to the contributors (if you want that is)

**Comment by ManiacalBilby** [comment]
Absolutely! Thanks for the reminder.
