### ISSUE TITLE
Better image assets

### ISSUE THREAD

**Issue by lmcjt37** [lmcjt37/curated-tv-and-film#86]
Most of the current images show black letter boxing.

These should be replaced with better images for the respective show or film.

**Comment by diddy225** [comment]
I'd love to help you with this. Can i get assigned?

**Comment by lmcjt37** [comment]
@diddy225 the black letter boxing has been fixed. But you could always try formatting the images to make them all uniform and help reduce the size of the files?

**Comment by diddy225** [comment]
I have updated image sizes for desktop and media rule.
