### ISSUE TITLE
Introduce a footer

### ISSUE THREAD

**Issue by lmcjt37** [lmcjt37/curated-tv-and-film#87]
Adding a footer to the bottom of the page to show some meta.

- Link back to this github repository
- Build version (This will mean that new PR's will require updates to the versions/ a build number increment will be needed in the future)
- link to contributors list

**Comment by jordan-skophammer** [comment]
On it!

**Comment by jordan-skophammer** [comment]
What should I put for the current build version?

**Comment by izanf** [comment]
#93
