### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by lmcjt37** [lmcjt37/curated-tv-and-film#88]
A simple logo which can be added to the header, repo and favicon.

**Comment by Rajat-dey** [comment]
Hello, what kind of logo you want for your header.

**Comment by harleo** [comment]
@lmcjt37 
Saw some people creating logos and thought I'd do one as well so you have a variety of choices.
Uploaded an SVG version so it's more flexible.
Ref: https://github.com/lmcjt37/curated-tv-and-film/pull/128

**Comment by JuliaSavych** [comment]
Please, check this :)
https://github.com/lmcjt37/curated-tv-and-film/pull/130/commits/f3713a4897678cb15d5b65017bc6781ff333bf55
